#   _____         _     __ _ _
# |_   _|_ _ ___| | __/ _(_) | ___
#   | |/ _` / __| |/ / |_| | |/ _ \
#   | | (_| \__ \   <|  _| | |  __/
#   |_|\__,_|___/_|\_\_| |_|_|\___|
#
# https://taskfile.dev
#

version: '3'

silent: true

##
## === ⚒️ Variables ====================================================
##

vars:
  #
  # TASKFILE
  VERSION: 1.0.0
  CONTRIBUTOR: "Benoit Foujols, Julien Pechberty"
  ENV: develop
  REPOSITORY: https://raw.githubusercontent.com/JPechberty/tpm-symfony
  #
  # SYSTEM
  PWD: $PWD
  #
  # SYMFONY
  SYMFONY_ENV: .env
##
## === ✅ TASKS ========================================================
##

tasks:
  default:
    cmds:
      - task: help

  ## === 🆘 HELP ======================================================

  help:
    desc: "Description des tâches disponibles"
    cmds:
      - echo "Bienvenu dans Taskfile pour Symfony"
      - echo "Merci aux contributeurs -> {{.CONTRIBUTOR}}"
      - echo "----------------------------------------------"
      - echo "Version de Taskfile {{.VERSION}}"
      - echo "Voici la description de votre systeme:"
      - echo 'Votre systeme "{{OS}}"'
      - echo 'Votre architecture "{{ARCH}}"'
      - echo "----------------------------------------------"
      - task --list

  update:
    desc: "Update taskfile config in your project"
    cmds:
      - curl -fsS {{.REPOSITORY}}/{{.ENV}}/Taskfile.yaml > ./_tpm/docker-compose/Taskfile.yaml
      - task: help

  ## === ⚙️ INTERFACES ================================================

  ## === 🧰 TOOLS =====================================================

  ## === 🧪 TESTING ===================================================
